

CREATE TABLE users(
id int(11) NOT NULL ,
username VARCHAR(50)NOT NULL,
password VARCHAR(255) NOT NULL,
fullname VARCHAR(255) NOT NULL
);

ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE users MODIFY id int(11) NOT NULL AUTO_INCREMENT;


CREATE TABLE links(
  id int(11) NOT NULL ,
  title VARCHAR(150) NOT NULL,
  url VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  user_id INT(11) ,
  createdd_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)  
);

ALTER TABLE links ADD PRIMARY KEY (id);
ALTER TABLE links MODIFY id int(11) NOT NULL AUTO_INCREMENT;